{{- range .Values.storageClasses}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
{{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ include "ceph-csi-rbd.name" . }}
    chart: {{ include "ceph-csi-rbd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
provisioner: {{ .Values.driverName }}
parameters:
  clusterID: {{ .clusterID }}
  pool: {{ .pool }}
  imageFeatures: {{ .imageFeatures }}
{{- if .tryOtherMounters }}
  tryOtherMounters: {{ .tryOtherMounters | quote}}
{{- end }}
{{- if .mounter }}
  mounter: {{ .mounter }}
{{- end }}
{{- if .cephLogDir }}
  cephLogDir: {{ .cephLogDir }}
{{- end }}
{{- if .cephLogStrategy }}
  cephLogStrategy: {{ .cephLogStrategy }}
{{- end }}
{{- if .dataPool }}
  dataPool: {{ .dataPool }}
{{- end }}
{{- if .volumeNamePrefix }}
  volumeNamePrefix: "{{ .volumeNamePrefix }}"
{{- end }}
{{- if .encrypted }}
  encrypted: "{{ .encrypted }}"
{{- end }}
{{- if .encryptionKMSID }}
  encryptionKMSID: {{ .encryptionKMSID }}
{{- end }}
{{- if .topologyConstrainedPools }}
  topologyConstrainedPools:
  {{ toYaml .topologyConstrainedPools | indent 4 -}}
{{- end }}
{{- if .mapOptions }}
  mapOptions: {{ .mapOptions }}
{{- end }}
{{- if .unmapOptions }}
  unmapOptions: {{ .unmapOptions }}
{{- end }}
  csi.storage.k8s.io/provisioner-secret-name: {{ .provisionerSecret }}
{{- if .provisionerSecretNamespace }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .provisionerSecretNamespace }}
{{ else }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
{{- end }}
  csi.storage.k8s.io/controller-expand-secret-name: {{ .controllerExpandSecret }}
{{- if .Values.storageClass.controllerExpandSecretNamespace }}
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .controllerExpandSecretNamespace }}
{{ else }}
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
{{- end }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .nodeStageSecret }}
{{- if .nodeStageSecretNamespace }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .nodeStageSecretNamespace }}
{{ else }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
{{- end }}
  csi.storage.k8s.io/fstype: {{ .fstype }}
reclaimPolicy: {{ .reclaimPolicy }}
allowVolumeExpansion: {{ .allowVolumeExpansion }}
{{- if .mountOptions }}
mountOptions:
  {{- range .mountOptions }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end -}}
